"""Feedback collector — collect, validate, and persist user feedback records.

See SPEC §4.6.5 (FeedbackData) and §5.1 (Phase 5 roadmap) for the full specification.

The :class:`FeedbackCollector` persists feedback to SQLite and provides
aggregate statistics for dashboards and learning pipelines.

Usage::

    from app.learning.feedback_collector import feedback_collector

    # Collect feedback from API or Web UI
    fid = feedback_collector.collect(
        session_id="sess_1",
        query_id="q_1",
        nl_input="订单总额",
        sql_generated="SELECT SUM(amount) FROM orders",
        sql_final="SELECT SUM(amount) FROM orders WHERE status='completed'",
        rating=4,
        feedback_text="缺少状态过滤",
    )

    # Query stats
    stats = feedback_collector.get_stats(domain="ecommerce")
    recent = feedback_collector.get_recent(limit=20, min_rating=3)
"""

from __future__ import annotations

import json
import sqlite3
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from app.models.feedback import DiffOp, FeedbackData

# ── SQL schema ────────────────────────────────────────────────────────────

CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS feedback_records (
    id              TEXT PRIMARY KEY,
    session_id      TEXT NOT NULL,
    query_id        TEXT NOT NULL,
    domain_id       TEXT DEFAULT '',
    nl_input        TEXT NOT NULL,
    sql_generated   TEXT NOT NULL,
    sql_final       TEXT,
    rating          INTEGER,
    feedback_text   TEXT,
    diff_count      INTEGER DEFAULT 0,
    diff_summary    TEXT,
    execution_success INTEGER DEFAULT 0,
    execution_time_ms INTEGER DEFAULT 0,
    user_cancelled  INTEGER DEFAULT 0,
    created_at      TEXT NOT NULL
);
"""

INDEX_DOMAIN_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_feedback_domain "
    "ON feedback_records(domain_id);"
)
INDEX_RATING_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_feedback_rating "
    "ON feedback_records(rating);"
)
INDEX_CREATED_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_feedback_created "
    "ON feedback_records(created_at);"
)


# ── FeedbackCollector ─────────────────────────────────────────────────────


class FeedbackCollector:
    """Collect, validate, persist, and query user feedback records.

    Uses SQLite for zero-config persistence (matching the project's
    convention of SQLite for local storage).  A module-level singleton
    ``feedback_collector`` is created at import time pointing at
    ``data/learning.db`` relative to the project root.
    """

    def __init__(self, db_path: str = "data/learning.db") -> None:
        """Initialise the collector and ensure the backing table exists.

        Args:
            db_path: Path to the SQLite database file.  Created if missing.
        """
        self._db_path = Path(db_path)
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        self._conn: sqlite3.Connection | None = None
        self._ensure_schema()

    # ── connection management ──────────────────────────────────────────

    def _get_conn(self) -> sqlite3.Connection:
        if self._conn is None:
            self._conn = sqlite3.connect(
                str(self._db_path), check_same_thread=False
            )
            self._conn.row_factory = sqlite3.Row
        return self._conn

    def _ensure_schema(self) -> None:
        conn = self._get_conn()
        conn.execute(CREATE_TABLE_SQL)
        conn.execute(INDEX_DOMAIN_SQL)
        conn.execute(INDEX_RATING_SQL)
        conn.execute(INDEX_CREATED_SQL)
        conn.commit()

    # ── collect ────────────────────────────────────────────────────────

    def collect(
        self,
        session_id: str,
        query_id: str,
        nl_input: str,
        sql_generated: str,
        sql_final: str = "",
        rating: int = 0,
        feedback_text: str = "",
        diff_operations: list[DiffOp] | None = None,
        execution_success: bool = False,
        execution_time_ms: int = 0,
        user_cancelled: bool = False,
        domain_id: str = "",
    ) -> str:
        """Persist a feedback record and return its unique ID.

        Accepts both keyword arguments (for convenience from Web UI) and
        a :class:`~app.models.feedback.FeedbackData` instance passed as
        the first positional argument.

        Args:
            session_id: Conversation session identifier.
            query_id: Unique query identifier.
            nl_input: The original natural-language query.
            sql_generated: The SQL originally generated by the system.
            sql_final: The user-confirmed (possibly edited) SQL.
            rating: 1–5 star rating.  0 means "no rating".
            feedback_text: Free-text feedback comment.
            diff_operations: List of :class:`~app.models.feedback.DiffOp`.
            execution_success: Whether the SQL executed successfully.
            execution_time_ms: Execution wall-clock time in milliseconds.
            user_cancelled: Whether the user aborted before completion.
            domain_id: Active domain at query time.

        Returns:
            The generated feedback record ID (UUID hex string).
        """
        record_id = uuid.uuid4().hex
        diffs = diff_operations or []
        diff_count = len(diffs)
        diff_summary = json.dumps(
            [
                {
                    "op_type": d.op_type,
                    "position": d.position,
                    "old_text": d.old_text,
                    "new_text": d.new_text,
                    "length": d.length,
                }
                for d in diffs
            ],
            ensure_ascii=False,
        )

        conn = self._get_conn()
        conn.execute(
            """INSERT INTO feedback_records
               (id, session_id, query_id, domain_id, nl_input, sql_generated,
                sql_final, rating, feedback_text, diff_count, diff_summary,
                execution_success, execution_time_ms, user_cancelled, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                record_id,
                session_id,
                query_id,
                domain_id,
                nl_input.strip(),
                sql_generated.strip(),
                (sql_final or "").strip(),
                rating if 1 <= rating <= 5 else 0,
                (feedback_text or "").strip(),
                diff_count,
                diff_summary,
                1 if execution_success else 0,
                execution_time_ms,
                1 if user_cancelled else 0,
                datetime.now(UTC).isoformat(),
            ),
        )
        conn.commit()
        return record_id

    def collect_from_dataclass(self, fb: FeedbackData) -> str:
        """Persist a :class:`~app.models.feedback.FeedbackData` instance.

        Args:
            fb: The feedback dataclass to persist.

        Returns:
            The generated feedback record ID.
        """
        return self.collect(
            session_id=fb.session_id,
            query_id=fb.query_id,
            nl_input=fb.nl_input,
            sql_generated=fb.sql_generated,
            sql_final=fb.sql_final or "",
            rating=fb.rating or 0,
            feedback_text=fb.feedback_text or "",
            diff_operations=fb.diff_operations,
            execution_success=fb.execution_success,
            execution_time_ms=fb.execution_time_ms,
            user_cancelled=fb.user_cancelled,
        )

    # ── query ──────────────────────────────────────────────────────────

    def get_recent(
        self,
        limit: int = 50,
        domain: str = "",
        min_rating: int = 0,
    ) -> list[dict[str, Any]]:
        """Return the most recent feedback records.

        Args:
            limit: Maximum number of records to return.
            domain: Optional domain filter.
            min_rating: Minimum rating (inclusive).  0 = no filter.

        Returns:
            List of dicts with all feedback record columns.
        """
        conditions: list[str] = []
        params: list[Any] = []

        if domain:
            conditions.append("domain_id = ?")
            params.append(domain)
        if min_rating > 0:
            conditions.append("rating >= ?")
            params.append(min_rating)

        where = ("WHERE " + " AND ".join(conditions)) if conditions else ""
        sql = (
            f"SELECT * FROM feedback_records {where} "
            "ORDER BY created_at DESC LIMIT ?"
        )
        params.append(limit)

        conn = self._get_conn()
        rows = conn.execute(sql, params).fetchall()
        return [dict(r) for r in rows]

    def get_by_id(self, record_id: str) -> dict[str, Any] | None:
        """Look up a single feedback record by ID."""
        conn = self._get_conn()
        row = conn.execute(
            "SELECT * FROM feedback_records WHERE id = ?", (record_id,)
        ).fetchone()
        return dict(row) if row else None

    # ── stats ──────────────────────────────────────────────────────────

    def get_stats(self, domain: str = "") -> dict[str, Any]:
        """Return aggregate feedback statistics.

        Args:
            domain: Optional domain filter.

        Returns:
            Dict with ``total``, ``avg_rating``, ``by_rating`` (list),
            ``success_rate``, ``cancel_rate``, ``with_feedback``,
            ``avg_edit_count``, ``domain_id``.
        """
        domain_filter = "WHERE domain_id = ?" if domain else ""
        params: list[Any] = ([domain] if domain else [])

        conn = self._get_conn()

        total_row = conn.execute(
            f"SELECT COUNT(*) AS n FROM feedback_records {domain_filter}",
            params,
        ).fetchone()
        total = total_row["n"] if total_row else 0

        if total == 0:
            return {
                "total": 0,
                "avg_rating": 0.0,
                "by_rating": [],
                "success_rate": 0.0,
                "cancel_rate": 0.0,
                "with_feedback": 0,
                "avg_edit_count": 0.0,
                "domain_id": domain or "*",
            }

        rating_cond = f"{domain_filter} AND rating > 0" if domain_filter else "WHERE rating > 0"
        avg_row = conn.execute(
            f"SELECT AVG(CAST(rating AS REAL)) AS a FROM feedback_records {rating_cond}",
            params,
        ).fetchone()
        avg_rating = round(avg_row["a"], 2) if avg_row and avg_row["a"] else 0.0

        by_rating_rows = conn.execute(
            f"SELECT rating, COUNT(*) AS n FROM feedback_records "
            f"{domain_filter} GROUP BY rating ORDER BY rating",
            params,
        ).fetchall()
        by_rating = [{"rating": r["rating"], "count": r["n"]} for r in by_rating_rows]

        succ_cond = (
            f"{domain_filter} AND execution_success = 1"
            if domain_filter else "WHERE execution_success = 1"
        )
        success_row = conn.execute(
            f"SELECT COUNT(*) AS n FROM feedback_records {succ_cond}",
            params,
        ).fetchone()
        success_rate = round(success_row["n"] / total * 100, 1) if success_row else 0.0

        canc_cond = (
            f"{domain_filter} AND user_cancelled = 1"
            if domain_filter else "WHERE user_cancelled = 1"
        )
        cancel_row = conn.execute(
            f"SELECT COUNT(*) AS n FROM feedback_records {canc_cond}",
            params,
        ).fetchone()
        cancel_rate = round(cancel_row["n"] / total * 100, 1) if cancel_row else 0.0

        text_cond = (
            f"{domain_filter} AND feedback_text != ''"
            if domain_filter else "WHERE feedback_text != ''"
        )
        text_row = conn.execute(
            f"SELECT COUNT(*) AS n FROM feedback_records {text_cond}",
            params,
        ).fetchone()
        with_feedback = text_row["n"] if text_row else 0

        edit_row = conn.execute(
            f"SELECT AVG(CAST(diff_count AS REAL)) AS a FROM feedback_records "
            f"{domain_filter}",
            params,
        ).fetchone()
        avg_edit_count = round(edit_row["a"], 2) if edit_row and edit_row["a"] else 0.0

        return {
            "total": total,
            "avg_rating": avg_rating,
            "by_rating": by_rating,
            "success_rate": success_rate,
            "cancel_rate": cancel_rate,
            "with_feedback": with_feedback,
            "avg_edit_count": avg_edit_count,
            "domain_id": domain or "*",
        }

    def export_for_analysis(
        self, domain: str = "", min_rating: int = 0
    ) -> list[dict[str, Any]]:
        """Export all feedback records for external analysis.

        Args:
            domain: Optional domain filter.
            min_rating: Minimum rating filter.

        Returns:
            List of all matching feedback record dicts.
        """
        conditions: list[str] = []
        params: list[Any] = []

        if domain:
            conditions.append("domain_id = ?")
            params.append(domain)
        if min_rating > 0:
            conditions.append("rating >= ?")
            params.append(min_rating)

        where = ("WHERE " + " AND ".join(conditions)) if conditions else ""
        conn = self._get_conn()
        rows = conn.execute(
            f"SELECT * FROM feedback_records {where} ORDER BY created_at DESC",
            params,
        ).fetchall()
        return [dict(r) for r in rows]

    # ── helpers ────────────────────────────────────────────────────────

    def count(self, domain: str = "") -> int:
        """Return the total number of feedback records."""
        if domain:
            row = self._get_conn().execute(
                "SELECT COUNT(*) AS n FROM feedback_records WHERE domain_id = ?",
                (domain,),
            ).fetchone()
        else:
            row = self._get_conn().execute(
                "SELECT COUNT(*) AS n FROM feedback_records"
            ).fetchone()
        return row["n"] if row else 0

    def close(self) -> None:
        """Close the underlying database connection."""
        if self._conn:
            self._conn.close()
            self._conn = None

    def __del__(self) -> None:
        self.close()


# ── module-level singleton ────────────────────────────────────────────────

feedback_collector = FeedbackCollector()
